### PR TITLE
Get test suite to compile on macos and CI it

### LINKED ISSUE #75: Test-suite fails to build on OS X
Note I'm using Nix on OS X.

```
$ cabal build
Preprocessing library for inline-c-cpp-0.2.2.1..
Building library for inline-c-cpp-0.2.2.1..
ignoring (possibly broken) abi-depends field for packages
Preprocessing test suite 'tests' for inline-c-cpp-0.2.2.1..
Building test suite 'tests' for inline-c-cpp-0.2.2.1..
[1 of 1] Compiling Main             ( test/tests.hs, dist/build/tests/tests-tmp/Main.o )
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]

/var/folders/8m/tqlhlzrd4lsbb8r3j9zw7wsw0000gn/T/ghc13912_0/ghc_4.cpp:127:8: error:
     warning: generalized initializer lists are a C++11 extension [-Wc++11-extensions]
    |
127 | return {};
    |        ^
return {};
       ^~

/var/folders/8m/tqlhlzrd4lsbb8r3j9zw7wsw0000gn/T/ghc13912_0/ghc_4.cpp:127:8: error:
     error: scalar initializer cannot be empty
    |
127 | return {};
    |        ^
return {};
       ^~

... cut ...

12 warnings and 12 errors generated.

<no location info>: error:
    `cc' failed in phase `C Compiler'. (Exit code: 1)
```

### PR DESCRIPTION
**Pull request by domenkozar**
Fixes #75 with working around Cabal bug.

But the test suite fails:

```
Basic C++
Hello, world!3
  Hello World
Exception handling
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: C++ error message                               
```

### CODE REVIEW

**Comment by bitonic** [comment]
for the record, I'm happy to merge once it passes. I'm even able to test myself in 2 weeks once I have my macbook around :upside_down_face: .

**Comment by domenkozar** [comment]
I've applied the workaround for https://gitlab.haskell.org/ghc/ghc/issues/11829 but apparently, I'm doing something wrong or the fix should be different.

**Comment by domenkozar** [comment]
Due to https://gitlab.haskell.org/ghc/ghc/issues/14784 I'm no longer convinced this can be fixed for darwin in GHC 8.4 and 8.2, but GHC 8.6 does run tests succesfully :)

**Comment by bitonic** [comment]
@domenkozar thanks!

**Pull request merged**
