### PR TITLE
inline-c-objc package for Objective-C support (fixes #142)

### LINKED ISSUE #142: Objective-C support
What would it take to support Objective-C too?

### PR DESCRIPTION
**Pull request by yairchu**
Let me know if anything should be done differently.

Note that I believe this will mostly be used to interface with macOS/iOS APIs, so I haven't tried testing it platforms other than macOS.

### CODE REVIEW

**Comment by junjihashimoto** [comment]
Hi, inline-c has a flag to parse c++. If this test does not work, you should update the parser of inline-c.
https://github.com/fpco/inline-c/blob/master/inline-c/src/Language/C/Types/Parse.hs#L126

**Comment by yairchu** [comment]
> If this test does not work

Which test?

**Comment by bitonic** [comment]
Thanks, I'll try to take a look this weekend.

**Comment by bitonic** [comment]
Thanks!

**Comment by bitonic** [comment]
https://hackage.haskell.org/package/inline-c-objc-0.1.0.0

**Pull request merged**
